version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:15.11.5-ee.0'
    container_name: gitlab-ee
    restart: always
    hostname: 'gitlab.lan'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.lan:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '80:8929'
      - '2224:22'
    volumes:
      - '/home/coup/license/gitlab-license/license_key.pub:/opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub'
      # - '$GITLAB_HOME/config:/etc/gitlab'
      # - '$GITLAB_HOME/logs:/var/log/gitlab'
      # - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
